/*
	Code:			hdf5mock.h
	Author:         Walter A. Santos Jr. (walter.augusto@gmail.com)
	Last update:	12/09/2012
	Version: 		0.1
	Description: 	Code with utility functions to read and extract hdf5 mock files generated by Alex/Euclid.
					Makes use of hdf5 lib (http://www.hdfgroup.org/)
	Usage:			Header/Library file. Include "hdf5mock.h" to use in other C/C++ codes.
					Source codes are in hdf5mock.cpp
	Compile (in VS): 
*/

#include <vector>
#include <fstream>
#include <iostream>
#include <string>

#include "H5Cpp.h"

#ifndef HDF5MOCK_H
#define HDF5MOCK_H



namespace hdf5mock {

	int getNumLines(const H5::H5File file, const H5::DataSpace dataspace);
	std::string getType(const std::string filename, const std::string column);
	
	std::vector<double> readColumnDouble(const std::string filename, const std::string column);
	std::vector<int> readColumnInt(const std::string filename, const std::string column);
	std::vector<long long> readColumnLongLong(const std::string filename, const std::string column);
	std::vector<float> readColumnFloat(const std::string filename, const std::string column);	
	
}

#endif // HDF5MOCK_H